site_name: BS Scheduler
repo_url: https://github.com/ancestor-mithril/bs-scheduler

theme:
  name: "material"

plugins:
  - mkdocstrings

nav:
  - Home: README.md
  - API Documentation: reference.md
  - Tutorials: tutorials.md
  - Schedule Visuals: plots.md
